### ISSUE TITLE
Search for organization names not searching substrings

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/imago#33]
The [documentation](http://docs.opencivicdata.org/en/latest/api/search.html#organization-search) for organization search says that the API will search for substrings. Doesn't seem to be happening.

* http://api.opencivicdata.org/organizations/?name=Illinois&apikey=APIKEY
* http://api.opencivicdata.org/organizations/?name__icontains=Illinois&apikey=APIKEY

**Comment by paultag** [comment]
Yep! Thanks, @jpmckinney - closing for that other bug
