### ISSUE TITLE
bill search on sponsors.id not working

### ISSUE THREAD

**Issue by dcloud** [opencivicdata/imago#34]
`curl -X "GET" "https://api.opencivicdata.org/bills/?sponsors.id=ocd-person%2F3b5daa7c-f127-472f-9bde-39d80f18e907&fields=id%2Ctitle"`

will return an http **500**.

**Comment by dcloud** [comment]
Internally raises an unhanded `django.core.exceptions.FieldError: Cannot resolve keyword 'sponsors.id' into field.` error. I *believe* this happens on `PublicListEndpoint` near line **284** where `self.filter` is run.

Not sure if imago was supposed to support sub/related object searches using dot notation or if there is supposed to be a generated field.

**Comment by paultag** [comment]
The fact this 500s is the bug here - we should get clean errors on this stuff when we put things into the API

**Comment by dcloud** [comment]
I'll tackle some of this error nonsense
