### ISSUE TITLE
legislative_session_id in fields for bills endpoint triggers a 500 error

### ISSUE THREAD

**Issue by dcloud** [opencivicdata/imago#35]
**500**: `curl -X "GET" "https://api.opencivicdata.org/bills/?fields=id%2Ctitle%2Clegislative_session_id"`

(yes I'm setting X-APIKEY)

`legislative_session_id` is in the default fields on the *BillDetail* view.

**Comment by dcloud** [comment]
The error gets thrown when the response is passed to `Http200` for JSON serialization. `legislative_session_id` is a python UUID object, and the default encoder doesn't know how to serialize that object.

**Comment by paultag** [comment]
Ah, yikes. If that's the case, let's remove it from the serialization, or
something.

On Tue, Apr 21, 2015 at 3:25 PM, Daniel Cloud <notifications@github.com>
wrote:

> The error gets thrown when the response is passed to Http200 for JSON
> serialization. legislative_session_id is a python UUID object, and the
> default encoder doesn't know how to serialize that object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/imago/issues/35#issuecomment-94912260>.
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by mileswwatkins** [comment]
@dcloud, your commit closes the issue, right?

**Comment by mileswwatkins** [comment]
AFK confirmation with @dcloud :+1:
