### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/imago#57]
Attempting to get this event: http://api.opencivicdata.org/ocd-event/005454ab-ddcd-4d95-bd22-1e121f0a73a1/ returns a 500 Error

The event is listed under http://api.opencivicdata.org/events/?jurisdiction_id=ocd-jurisdiction/country:us/state:il/place:chicago/government

**Comment by fgregg** [comment]
Other events in the same list load fine.

**Comment by jpmckinney** [comment]
Re-open on https://github.com/opencivicdata/api.opencivicdata.org/issues if still an issue.
