### ISSUE TITLE
500 error for some NYC events

### ISSUE THREAD

**Issue by cathydeng** [opencivicdata/imago#63]
there are server errors for some event pages (but not all) from the [nyc events listing](http://api.opencivicdata.org/events/?jurisdiction_id=ocd-jurisdiction/country:us/state:ny/place:new_york/government)

example: [ocd-event/001297df-b47c-40b2-a1b0-f31afb8082a1](http://api.opencivicdata.org/ocd-event/001297df-b47c-40b2-a1b0-f31afb8082a1/)(3rd event in the listing)

@mileswwatkins @rshorey

**Comment by jpmckinney** [comment]
@cathydeng I think this issue should be on https://github.com/opencivicdata/api.opencivicdata.org

Imago is just the software for the API, not the API itself.

**Comment by cathydeng** [comment]
thanks @jpmckinney - moved the issue
